version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - prealloc
    - revive
    - staticcheck
    - unused
  exclusions:
    presets:
      - comments

formatters:
  enable:
    - gofumpt
    - goimports
